/**
 * explain.js — Turn probe results into plain English.
 *
 * Port of splainfish/explain.py. Produces the same JSON shape the HTML viewer
 * already consumes, so reports generated by the Python CLI and by the browser
 * render identically.
 */

import { MoveQuality } from './classifier.js';
import { WHITE } from './nnue/features.js';

// ---------------------------------------------------------------------------
// Classification
// ---------------------------------------------------------------------------

/** Classify move quality from the eval delta (White's perspective). */
function classifyDelta(deltaCp, movingColor) {
  const loss = movingColor === WHITE ? -deltaCp : deltaCp;
  if (loss <= 10)  return MoveQuality.BEST;
  if (loss <= 30)  return MoveQuality.EXCELLENT;
  if (loss <= 60)  return MoveQuality.GOOD;
  if (loss <= 120) return MoveQuality.INACCURACY;
  if (loss <= 250) return MoveQuality.MISTAKE;
  return MoveQuality.BLUNDER;
}

export const QUALITY_GLYPH = {
  [MoveQuality.BEST]: '', [MoveQuality.EXCELLENT]: '!', [MoveQuality.GOOD]: '',
  [MoveQuality.INACCURACY]: '?!', [MoveQuality.MISTAKE]: '?',
  [MoveQuality.BLUNDER]: '??', [MoveQuality.FORCED]: '',
};

export const QUALITY_LABEL = {
  [MoveQuality.BEST]: 'Best move', [MoveQuality.EXCELLENT]: 'Excellent',
  [MoveQuality.GOOD]: 'Good', [MoveQuality.INACCURACY]: 'Inaccuracy',
  [MoveQuality.MISTAKE]: 'Mistake', [MoveQuality.BLUNDER]: 'Blunder',
  [MoveQuality.FORCED]: 'Forced',
};

export const QUALITY_COLOR = {
  [MoveQuality.BEST]: '#5aa65a', [MoveQuality.EXCELLENT]: '#96bc4b',
  [MoveQuality.GOOD]: '#b0b0b0', [MoveQuality.INACCURACY]: '#f0c040',
  [MoveQuality.MISTAKE]: '#e07030', [MoveQuality.BLUNDER]: '#c03030',
  [MoveQuality.FORCED]: '#808080',
};

// ---------------------------------------------------------------------------
// English templates
// ---------------------------------------------------------------------------

const cpStr = (cp) => (Math.abs(cp) / 100).toFixed(1);

const GROUP_TEMPLATES = {
  'own pawn shield': {
    negative: "This move weakened the {mover} king's pawn cover, leaving it more exposed to attacks.",
    positive: "This move improved the {mover} king's pawn shield, making it harder to attack.",
  },
  'enemy pawn advance near king': {
    negative: 'Enemy pawns moved closer to the {mover} king, increasing the threat of a breakthrough.',
    positive: 'The {enemy} pawn pressure near the king was reduced.',
  },
  'enemy queen threatening king area': {
    negative: 'The {enemy} queen now has more influence near the {mover} king, creating serious attacking possibilities.',
    positive: "The {enemy} queen's access to the {mover} king's area was reduced.",
  },
  'enemy rook pressure near king': {
    negative: 'A {enemy} rook gained access to lines near the {mover} king, increasing the danger.',
    positive: 'The {enemy} rook pressure near the {mover} king was relieved.',
  },
  'enemy knight attacking king zone': {
    negative: "A {enemy} knight moved into the {mover} king's zone, directly threatening key squares around it.",
    positive: "A {enemy} knight was removed from the {mover} king's zone.",
  },
  'enemy bishop attacking king zone': {
    negative: "A {enemy} bishop now targets the {mover} king's zone from a distance.",
    positive: "A {enemy} bishop's diagonal toward the {mover} king was closed.",
  },
  'enemy queen activity': {
    negative: 'The {enemy} queen gained a more active position, increasing overall pressure.',
    positive: "The {enemy} queen's activity was restricted.",
  },
  'enemy rook activity': {
    negative: 'A {enemy} rook became more active, potentially targeting open lines.',
    positive: "The {enemy} rook's activity was reduced.",
  },
  'enemy knight activity': {
    negative: 'A {enemy} knight reached a more active square, controlling more of the board.',
    positive: "A {enemy} knight's influence was reduced.",
  },
  'enemy bishop activity': {
    negative: 'A {enemy} bishop opened up a more powerful diagonal.',
    positive: "A {enemy} bishop's diagonal was blocked or restricted.",
  },
  'own queen activity / coordination': {
    negative: 'The {mover} queen became less active or lost coordination with other pieces.',
    positive: 'The {mover} queen moved to a more active square, increasing its influence.',
  },
  'own rook activity': {
    negative: 'A {mover} rook lost activity or access to open lines.',
    positive: 'A {mover} rook gained access to an open or semi-open file.',
  },
  'own knight activity / coordination': {
    negative: 'A {mover} knight moved to a less effective square.',
    positive: 'A {mover} knight reached a strong, centralized square.',
  },
  'own bishop activity / coordination': {
    negative: "A {mover} bishop's diagonal was blocked or became less effective.",
    positive: 'A {mover} bishop was activated on a more powerful diagonal.',
  },
  'own pawn structure': {
    negative: 'This move created a weakness in the {mover} pawn structure.',
    positive: 'This move improved the {mover} pawn structure.',
  },
  'enemy pawn structure': {
    negative: 'The {enemy} pawn structure became more solid or threatening.',
    positive: 'The {enemy} pawn structure was weakened.',
  },
  'king position': {
    negative: 'The king moved to a less safe square.',
    positive: 'The king moved to a safer or more active square.',
  },
  'own queen near king (defensive)': {
    negative: 'The {mover} queen moved away from a defensive role near the king.',
    positive: 'The {mover} queen took up a defensive position near the king.',
  },
};

const FALLBACK_TEMPLATE = {
  negative: 'The {mover} position became less favourable in terms of {group}.',
  positive: 'The {mover} position improved in terms of {group}.',
};

function fmt(tmpl, { mover, enemy, group }) {
  return tmpl
    .replaceAll('{mover}', mover)
    .replaceAll('{enemy}', enemy)
    .replaceAll('{group}', group);
}

function sentence(group, direction, mover, enemy) {
  const templates = GROUP_TEMPLATES[group] ?? FALLBACK_TEMPLATE;
  const tmpl = templates[direction] ?? FALLBACK_TEMPLATE[direction];
  return fmt(tmpl, { mover, enemy, group });
}

// ---------------------------------------------------------------------------
// Complexity detector
// ---------------------------------------------------------------------------

/**
 * A position is 'complex' (no single dominant explanation) when the top group
 * accounts for under 40% of total absolute attribution, or 5+ groups each
 * contribute over 10%.
 */
function isComplexPosition(groups) {
  if (!groups.length) return false;
  const total = groups.reduce((s, g) => s + Math.abs(g.contribution), 0);
  if (total < 1e-6) return false;
  const topShare = Math.abs(groups[0].contribution) / total;
  const significant = groups.filter((g) => Math.abs(g.contribution) / total > 0.1).length;
  return topShare < 0.4 || significant >= 5;
}

// ---------------------------------------------------------------------------
// Builder
// ---------------------------------------------------------------------------

const signed = (cp) => (cp >= 0 ? '+' : '') + (cp / 100).toFixed(2);

/**
 * Build the Explanation record for one move.
 * Mirrors explain.build(); the returned keys match the JSON the viewer reads.
 */
export function build({
  result, moveSan, moveUci, fenBefore, fenAfter, moveNumber, movingColor,
  bestMoveSan = null, bestLineSan = null,
  sfEvalBefore = null, sfEvalAfter = null,
}) {
  const mover = movingColor === WHITE ? 'White' : 'Black';
  const enemy = movingColor === WHITE ? 'Black' : 'White';

  // Stockfish's evals drive classification and display; the internal forward
  // pass only sets attribution direction.
  const evalBefore = sfEvalBefore ?? result.evalBeforeCp;
  const evalAfter  = sfEvalAfter  ?? result.evalAfterCp;
  const sfDelta = evalAfter - evalBefore;

  const quality = classifyDelta(sfDelta, movingColor);
  const lossCp = Math.max(0, movingColor === WHITE ? -sfDelta : sfDelta);

  const groups = result.groupedAttributions;
  const complex = isComplexPosition(groups);

  const glyph = QUALITY_GLYPH[quality];
  const displayMove = glyph ? `${moveSan}${glyph}` : moveSan;

  let simpleHeadline;
  if (quality === MoveQuality.BEST) {
    simpleHeadline = `Best move: ${displayMove}`;
  } else if (quality === MoveQuality.EXCELLENT || quality === MoveQuality.GOOD) {
    simpleHeadline = `${QUALITY_LABEL[quality]}: ${displayMove}`;
  } else if (quality === MoveQuality.INACCURACY) {
    simpleHeadline = `Inaccuracy: ${displayMove} — about ${cpStr(lossCp)} pawns below best`;
  } else if (quality === MoveQuality.MISTAKE) {
    simpleHeadline = `Mistake: ${displayMove} — loses about ${cpStr(lossCp)} pawns`;
  } else {
    simpleHeadline = `Blunder: ${displayMove} — loses about ${cpStr(lossCp)} pawns`;
  }

  const simpleParagraphs = [];

  if (quality === MoveQuality.BEST || quality === MoveQuality.EXCELLENT || quality === MoveQuality.GOOD) {
    // Display Stockfish's evals, never the internal forward-pass eval — the
    // latter's magnitude is unreliable on some nets (see README honesty).
    simpleParagraphs.push(
      `The evaluation barely changed (${signed(evalBefore)} → ` +
      `${signed(evalAfter)}), meaning this move maintained or ` +
      `improved ${mover}'s position.`,
    );
    if (groups.length) {
      simpleParagraphs.push(sentence(groups[0].group, groups[0].direction, mover, enemy));
    }
  } else if (complex) {
    simpleParagraphs.push(
      `The evaluation shifted about ${cpStr(lossCp)} pawns against ${mover}. ` +
      'This position is quite complex — several factors contributed to the evaluation change ' +
      'rather than one clear reason. The main themes were: ' +
      `${groups.slice(0, 3).map((g) => g.group).join(', ')}.`,
    );
    simpleParagraphs.push(
      'Switch to the detailed view to see a full breakdown of each contributing factor.',
    );
  } else {
    const topGroups = groups.slice(0, 2).filter((g) => Math.abs(g.contribution) > 0.01);
    if (topGroups.length) {
      const primary = topGroups[0];
      const s1 = sentence(primary.group, primary.direction, mover, enemy);
      const against = quality === MoveQuality.MISTAKE || quality === MoveQuality.BLUNDER
        ? 'against' : 'for';
      simpleParagraphs.push(
        `The evaluation moved ${cpStr(Math.abs(sfDelta))} pawns ${against} ${mover}. ${s1}`,
      );
      if (topGroups.length > 1) {
        const s2 = sentence(topGroups[1].group, topGroups[1].direction, mover, enemy);
        simpleParagraphs.push(`Additionally: ${s2.toLowerCase()}`);
      }
    }

    if (bestMoveSan && quality !== MoveQuality.BEST && quality !== MoveQuality.FORCED) {
      const line = bestLineSan ? bestLineSan.slice(0, 5).join(' ') : '';
      simpleParagraphs.push(
        `Stockfish preferred ${bestMoveSan} instead.` + (line ? ` Best line: ${line}` : ''),
      );
    }
  }

  const complexHeadline =
    `${QUALITY_LABEL[quality]}: ${displayMove}  [${signed(evalBefore)} → ${signed(evalAfter)}]`;

  const totalAttr = groups.reduce((s, g) => s + Math.abs(g.contribution), 0) || 1;
  const complexGroups = groups.map((g) => ({
    group: g.group,
    contribution_cp: Math.round((g.contribution / 100) * 100) / 100,
    direction: g.direction,
    pct_of_total: Math.round((Math.abs(g.contribution) / totalAttr) * 100 * 10) / 10,
    feature_count: g.featureCount,
    sentence: sentence(g.group, g.direction, mover, enemy),
  }));

  const complexNote =
    'Contributions are derived by back-projecting the eval delta through the NNUE ' +
    'network (L0→L2) to the input feature groups that changed between the two positions. ' +
    "The percentages show each group's share of the total attributed change. " +
    'Attribution shows relative direction and emphasis, not calibrated centipawns; ' +
    "the evaluation numbers shown are Stockfish's.";

  return {
    move_san: moveSan,
    move_uci: moveUci,
    fen_before: fenBefore,
    fen_after: fenAfter,
    move_number: moveNumber,
    color: movingColor === WHITE ? 'white' : 'black',
    eval_before_cp: evalBefore,
    eval_after_cp: evalAfter,
    delta_cp: sfDelta,
    quality,
    quality_label: QUALITY_LABEL[quality],
    quality_glyph: glyph,
    quality_color: QUALITY_COLOR[quality],
    is_complex: complex,
    simple_headline: simpleHeadline,
    simple_paragraphs: simpleParagraphs,
    complex_headline: complexHeadline,
    complex_groups: complexGroups,
    complex_note: complexNote,
    top_groups: groups.slice(0, 5).map((g) => g.group),
    best_move_san: bestMoveSan,
    best_line_san: bestLineSan ?? [],
    sf_eval_before: sfEvalBefore,
    sf_eval_after: sfEvalAfter,
  };
}
