#!/usr/bin/env python3
"""
gen_pieces_css.py — Build the chessground piece stylesheet from the vendored
rhosgfx SVG set, embedding each piece as a data URI.

Chessground renders pieces as <piece class="pawn white"> elements and expects a
stylesheet to supply the artwork via background-image. Embedding the SVGs as
data URIs means one stylesheet works both for the multi-file web app and for the
single-file self-contained report, which cannot reference external assets.

Usage:  python3 tools/gen_pieces_css.py [--out web/css/pieces.rhosgfx.css]
"""

from __future__ import annotations

import argparse
import base64
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
PIECE_DIR = REPO / "vendor" / "pieces-rhosgfx"

# chessground class names, keyed by the rhosgfx filename stem
ROLES = {
    "P": "pawn", "N": "knight", "B": "bishop",
    "R": "rook", "Q": "queen",  "K": "king",
}
COLORS = {"w": "white", "b": "black"}

HEADER = """/* =============================================================================
 * pieces.rhosgfx.css — GENERATED by tools/gen_pieces_css.py, do not edit.
 *
 * Piece artwork: rhosgfx by RhosGFX (https://rhosgfx.itch.io/)
 * Licensed CC0 1.0 Universal (public domain) — see vendor/pieces-rhosgfx/LICENSE
 *
 * Class names follow chessground's piece element convention.
 * ============================================================================= */
"""


def piece_data_uris() -> dict:
    """Return {"wP": data_uri, ...} for all 12 pieces. Used by render.py to
    build the self-contained report board without chessground."""
    out = {}
    for color_key, _ in COLORS.items():
        for role_key, _ in ROLES.items():
            svg = PIECE_DIR / f"{color_key}{role_key}.svg"
            if svg.is_file():
                out[f"{color_key}{role_key}"] = data_uri(svg)
    return out


def data_uri(svg_path: Path) -> str:
    """Base64 data URI for an SVG file.

    Base64 rather than percent-encoding: the rhosgfx SVGs contain quotes and '#'
    characters, which are fragile inside a CSS url() even when escaped.
    """
    raw = svg_path.read_bytes()
    b64 = base64.b64encode(raw).decode("ascii")
    return f"data:image/svg+xml;base64,{b64}"


def build_css() -> str:
    if not PIECE_DIR.is_dir():
        raise SystemExit(f"Piece directory not found: {PIECE_DIR}")

    out = [HEADER]
    missing = []

    for color_key, color in COLORS.items():
        for role_key, role in ROLES.items():
            svg = PIECE_DIR / f"{color_key}{role_key}.svg"
            if not svg.is_file():
                missing.append(svg.name)
                continue
            uri = data_uri(svg)
            out.append(
                f".cg-wrap piece.{role}.{color} {{\n"
                f"  background-image: url('{uri}');\n"
                f"}}\n"
            )

    if missing:
        raise SystemExit(f"Missing piece SVGs: {', '.join(missing)}")

    return "\n".join(out)


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--out", default=str(REPO / "web" / "css" / "pieces.rhosgfx.css"),
        help="Output CSS path",
    )
    args = ap.parse_args(argv)

    css = build_css()
    out_path = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(css, encoding="utf-8")

    kb = len(css.encode("utf-8")) / 1024
    print(f"Wrote {out_path} ({kb:.1f} KB, {len(ROLES) * len(COLORS)} pieces)")


if __name__ == "__main__":
    sys.exit(main())
